@host=http://localhost:4000

### get all notes
GET {{host}}/notes

### get specific user notes

GET {{host}}/notes/608fae0f5169ee4b54f2f889
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbG1pYTAxMiIsImlkIjoiNjA4ZmU4OTBmMTEwYzg0YWMwNTUxNzQ2IiwiaWF0IjoxNjIwMDQ1MTIxLCJleHAiOjE2MjAwNTIzMjF9.sVNWQlUakXJ9aJJT9ZPG6W_veAd9NfVDvoUe4h8Z6Yk

{
    "userId":"608fae0f5169ee4b54f2f889"
}

### add a note

POST {{host}}/notes
Content-Type: application/json

{   
    "userId":"608fae0f5169ee4b54f2f889",
    "title":"Do you really need a second monitor to code?",
    "description":"Many developers use a multi-monitor system. Typically, there’ll be a primary monitor for the code editor and an auxiliary monitor for additional things. So, should you invest in a secondary monitor, or is it just a fad?"
}


###
Get {{host}}/notes/specific-note/608faadae3af93122cc10233

###
PATCH {{host}}/notes/yuuur2322ddf

###
DELETE {{host}}/notes/67eee234-908u2

###
POST {{host}}/sign-up
Content-Type: application/json

{
    "username":"dalmia012345",
    "email":"dalmia012345@gmail.com",
    "password":"dalmia012345"
}

###
POST {{host}}/sign-in
Content-Type: application/json

{
    "username":"dalmia012",
    "password":"dalmia012"
}

###
DELETE {{host}}/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbG1pYTAxMiIsImlhdCI6MTYyMDAyNjgyNiwiZXhwIjoxNjIwMDI2ODQ2fQ.L7PVk9XtMFEtGupy4B-KqmLAnnicMBaIYNkiT2GOQDc

{
    "username":"dalmia012"
}

###

PATCH {{host}}/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbG1pYTAxMiIsImlhdCI6MTYyMDAyODI0OCwiZXhwIjoxNjIwMDM1NDQ4fQ.9IsQm7d9DQYwq3p_oey7iTKLZHv1pyUxOlGwu8zqhWA

{
    "username":"dalmia012",
    "password":"dalmia@01200",
    "new_password":"dalmia012"
}