GET http://localhost:4000/notes

###

POST http://localhost:4000/notes
Content-Type: application/json

{   
    "userId":"608eecf763d8f44f98fd0067",
    "title":"Nestle",
    "description":"mainly a chocolate company",
    "label":["chocolate"]
}


###
Get http://localhost:4000/notes/eerreeee

###
PATCH http://localhost:4000/notes/yuuur2322ddf

###
DELETE http://localhost:4000/notes/67eee234-908u2

###
POST http://localhost:4000/sign-up
Content-Type: application/json

{
    "username":"dalmia01",
    "email":"dalmia@gmail.com",
    "password":"dalmia01"
}