GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "id":"5e64b9fa-0904-4b46-a0ad-5f02d2e50bde",
    "title":"Maggi",
    "description":"every evening snack",
    "amount":"22"
}


###
Get http://localhost:3000/products/eerreeee

###
PATCH http://localhost:3000/products/yuuur2322ddf

###
DELETE http://localhost:3000/products/67eee234-908u2